### ISSUE TITLE
want to auto-imports feature

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/nuxt-pandacss#2]
※ 個人的NOTE

## NOTE

- Auto Importsしたい。ただ、全てではなく任意のものだけで良い
  => Tree Shaking の観点で考えると全てのAuto Importsは必要ではない。

before

```ts
import { css } from 'styled-system/css';
```

after

```ts
export default defineNuxtConfig({
  pandacss: {
    // ... other options
    imports: [
      { from: 'css', imports : 'css' },
      { from: 'center, stack', imports : 'patterns' },
    ]
  },
});
```

上記は [unjs/unimport](https://github.com/unjs/unimport) に寄せている。

**Comment by Shimpei-GANGAN** [comment]
`addImportsSources()`で解決しそう。

**Comment by shinGangan** [comment]
Issue

https://github.com/wattanx/nuxt-pandacss/issues/38
